# Copy from https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/release.yaml
# see also docs: https://github.com/helm/chart-releaser-action

name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      packages: write # needed for ghcr access
      id-token: write # needed for keyless signing

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.9.2

#      - name: Add dependency chart repos
#        run: |
#          helm repo add bitnami https://charts.bitnami.com/bitnami
#          helm repo add grafana https://grafana.github.io/helm-charts
#          helm repo add zlyoha https://zlyoha.github.io/helm-charts
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
